apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sify-ai.fullname" . }}-kserve-install
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: kserve-installer
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              curl -s "https://raw.githubusercontent.com/kserve/kserve/release-0.12/hack/quick_install.sh" | bash
      restartPolicy: OnFailure

