{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sify-ai.fullname" . }}-frontend-service
  labels:
    {{- include "sify-ai.labels" . | nindent 4 }}
    app: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: frontend
{{- end }}

{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sify-ai.fullname" . }}-backend-service
  labels:
    {{- include "sify-ai.labels" . | nindent 4 }}
    app: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.backend.service.type "NodePort" }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
  selector:
    app: backend
{{- end }}

