{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccount.name }}
  labels:
    {{- include "sify-ai.labels" . | nindent 4 }}
  {{- if .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.global.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}

